name: Merge to main

on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Run tests
    uses: twilio-labs/plugin-webhook/.github/workflows/run-tests.yml@main

  release:
    name: Run release work
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Update npm to 8.x
        run: |
          npm i -g npm@8
      - name: Install Dependencies
        run: npm install
      - name: Setup CI Git User
        run: |
          git config user.name twilio-labs-ci
          git config user.email 65686990+twilio-labs-ci@users.noreply.github.com
      - name: "Create Pull Request or Publish to npm"
        uses: changesets/action@v1
        with:
          version: npm run version
          # publish: yarn release
          commit: "chore(release): version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}